# PARTE 1
    CREATE DATABASE VETERINARIA;
    USE VETERINARIA;

    # CREAR TRES TABLAS DEFINIDAS CON LA SIGUIENTE ESTRUCTURA:
        # MASCOTAS: ID, NOMBRE, ID_DUENIO, SERVICIO
    CREATE TABLE MASCOTAS(
        ID INT NOT NULL,
        NOMBRE VARCHAR(20),
        ID_DUENIO INT NOT NULL,
        SERVICIO VARCHAR(20)
    );

        # PERSONAS: ID, NOMBRE, APELLIDO,  COD_ZIP, TLF
    CREATE TABLE PERSONAS(
        ID INT NOT NULL,
        NOMBRE VARCHAR(20),
        APELLIDO VARCHAR(20),
        COD_ZIP INT NOT NULL,
        TLF VARCHAR(20)
    );

        # DIRECCIONES: ZIP, NOMBRE_ZONA, RUTA
    CREATE TABLE DIRECCIONES(
        ZIP INT NOT NULL,
        NOMBRE_ZONA VARCHAR(20),
        RUTA VARCHAR(30)
    );



# PARTE 2
    # AGREGAR UNA PK AL CAMPO ID EN LAS TABLAS MASCOTAS Y PERSONAS
    ALTER TABLE MASCOTAS ADD PRIMARY KEY(ID);
    ALTER TABLE PERSONAS ADD PRIMARY KEY (ID);
    ALTER TABLE DIRECCIONES ADD PRIMARY KEY (ZIP);

    # AGREGAR UNA FK AL CAMPO ID_DUENIO EN LA TABLA MASCOTAS QUE REFERENCIE AL CAMPO ID EN LA TABLA PERSONAS
    ALTER TABLE MASCOTAS ADD FOREIGN KEY (ID_DUENIO) REFERENCES PERSONAS(ID);
        ALTER TABLE MASCOTAS ADD CONSTRAINT FK_PERSONAS FOREIGN KEY (ID_DUENIO) REFERENCES PERSONAS(ID);

    # AGREGAR UNA FK AL CAMPO ZIP_COD EN LA TABLA PERSONAS QUE REFERENCIE AL CAMPO ZIP EN LA TABLA DIRECCIONES
    ALTER TABLE PERSONAS ADD FOREIGN KEY (ZIP_COD) REFERENCES DIRECCIONES(ZIP);
        ALTER TABLE PERSONAS ADD CONSTRAINT FK_DIRECCIONES FOREIGN KEY (ZIP_COD) REFERENCES DIRECCIONES(ZIP);

    # AGREGAR UNA COLUMNA LLAMADA EMAIL A LA TABLA PERSONAS
    ALTER TABLE PERSONAS ADD COLUMN EMAIL VARCHAR(20);

    # AGREGAR UNA UNIQUE CONSTRAINT A LA COLUMNA EMAIL DE LA TABLA PERSONAS
    ALTER TABLE PERSONAS ADD CONSTRAINT U_EMAIL UNIQUE (EMAIL);

    # CAMBIA EL NOMBRE A LA COLUMNA NOMBRE EN LA TABLA MASCOTAS POR PRIMER_NOMBRE
    ALTER TABLE MASCOTAS CHANGE NOMBRE PRIMER_NOMBRE VARCHAR(20);
        ALTER TABLE MASCOTAS RENAME COLUMN NOMBRE TO PRIMER_NOMBRE;

    # CAMBIA EL TIPO DE DATO A LA COLUMNA RUTA EN LA TABLA DIRECCIONES POR CHAR(12)
    ALTER TABLE DIRECCIONES MODIFY RUTA CHAR(12);