# AGREGAR Y QUITAR COLUMNAS

# ALTER TABLE <nombre tabla>
# ADD COLUMN <nombre columna> <tipo de dato> (tamaño)

# ALTER TABLE <nombre tabla>
# DROP COLUMN <nombre columna>;



USE SAKILA;

# CREAMOS UNA TABLA A PARTIR DE INFORMACIÓN YA ALMACENADA
CREATE TABLE KOI
    SELECT CITY_ID, PHONE, DISTRICT, LOCATION FROM ADDRESS;
SELECT * FROM KOI;

ALTER TABLE KOI DROP COLUMN DISTRICT;
SELECT * FROM KOI;

# AGREGAMOS UNA COLUMNA NUEVA
ALTER TABLE KOI
    ADD COLUMN NUEVO_DISTRITO VARCHAR(20);
